:: Currently not executed by Tron as I'm unsure if these will stall the script or not
:: If you can test these on a system with these products and let me know if it finishes
:: without interruptions or prompts, it'd be very helpful and I'll enable it for Tron


if exist "C:\Program Files (x86)\Monopoly\unins000.exe" ( start /wait "GS" "C:\Program Files (x86)\Monopoly\unins000.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\4 Elements II\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\4 Elements II\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Agatha Christie - Death on the Nile\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Agatha Christie - Death on the Nile\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Airport Mania\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Airport Mania\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Aloha TriPeaks\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Aloha TriPeaks\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Azkend 2 The World Beneath\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Azkend 2 The World Beneath\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Bejeweled 2 Deluxe\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Bejeweled 2 Deluxe\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Bejeweled 3\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Bejeweled 3\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Bounce Symphony\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Bounce Symphony\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Build-a-lot\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Build-a-lot\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Cradle Of Egypt Collectors Edition\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Cradle Of Egypt Collectors Edition\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Cradle of Rome 2\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Cradle of Rome 2\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Curse at Twilight\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Curse at Twilight\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Delicious Emilys Childhood Memories Premium Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Delicious Emilys Childhood Memories Premium Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Delicious Emilys True Love Premium Edition\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Delicious Emilys True Love Premium Edition\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Doras World Adventure\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Doras World Adventure\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Farm Frenzy\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Farm Frenzy\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Farm to Fork Collectors Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Farm to Fork Collectors Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Fishdom 3 Collectors Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Fishdom 3 Collectors Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Game Explorer Categories - genres\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Game Explorer Categories - genres\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Governor of Poker 2 Premium Edition\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Governor of Poker 2 Premium Edition\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\House of 1000 Doors Family Secrets\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\House of 1000 Doors Family Secrets\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Jewel Match 3\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Jewel Match 3\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\John Deere Drive Green\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\John Deere Drive Green\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\King Oddball\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\King Oddball\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Letters from Nowhere 2\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Letters from Nowhere 2\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\LUXOR Evolved\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\LUXOR Evolved\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Magic Academy\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Magic Academy\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Mahjongg Dimensions Deluxe\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Mahjongg Dimensions Deluxe\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Mystery PI - Curious Case of Counterfeit Cove\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Mystery PI - Curious Case of Counterfeit Cove\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Peggle Nights\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Peggle Nights\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Penguins!\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Penguins!\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Plants vs Zombies - Game of the Year\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Plants vs Zombies - Game of the Year\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Polar Bowler 1st Frame\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Polar Bowler 1st Frame\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Polar Bowler\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Polar Bowler\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Polar Golfer\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Polar Golfer\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Roads of Rome 3\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Roads of Rome 3\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Tales of Lagoona\Uninstall\Uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Tales of Lagoona\Uninstall\Uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\The Chronicles of Emerland Solitaire\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\The Chronicles of Emerland Solitaire\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\The Treasures of Mystery Island The Ghost Ship\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\The Treasures of Mystery Island The Ghost Ship\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Trinklit Supreme\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Trinklit Supreme\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Vacation Quest - Australia\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Vacation Quest - Australia\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Youda Jewel Shop\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Youda Jewel Shop\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildGames\Zumas Revenge\uninstall\uninstaller.exe" ( start /wait "GS" "C:\Program Files (x86)\WildGames\Zumas Revenge\uninstall\uninstaller.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - casual\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - casual\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - enthusiast\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - enthusiast\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - family\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - family\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - genres\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - genres\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - kids\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - kids\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - main\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - main\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - touch\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Game Explorer Categories - touch\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Touchpoints\acer\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Touchpoints\acer\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Touchpoints\asus\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Touchpoints\asus\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Touchpoints\hp\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Touchpoints\hp\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Touchpoints\toshiba\uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Touchpoints\toshiba\uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Web Link - Command and Conquer Tiberium Alliances\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Web Link - Command and Conquer Tiberium Alliances\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Web Link - DoubleDown Casino\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Web Link - DoubleDown Casino\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Web Link - Dragons Of Atlantis\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Web Link - Dragons Of Atlantis\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Web Link - Sushi Cat\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Web Link - Sushi Cat\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Web Link - The Godfather 5 Families\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Web Link - The Godfather 5 Families\Uninstall.exe" >nul 2>&1 )
if exist "C:\Program Files (x86)\WildTangent Games\Web Link - The Godfather Five Families\Uninstall.exe" ( start /wait "GS" "C:\Program Files (x86)\WildTangent Games\Web Link - The Godfather Five Families\Uninstall.exe" >nul 2>&1 )
